/** @type {import('prettier').Config} */
export default {
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'consistent',
  jsxSingleQuote: false,
  trailingComma: 'all',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: true,
  endOfLine: 'lf',
  singleAttributePerLine: true,
  tailwindStylesheet: './app/assets/css/tailwind.css',
  plugins: ['prettier-plugin-tailwindcss', '@prettier/plugin-oxc'],
};
